import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { Manrope } from 'next/font/google';
import { Inter } from 'next/font/google';
import "./globals.css";
import Sidebar from "./components/sidebar/Sidebar";
import MobileNav from "./components/nav/MobileNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Manrope(
  { subsets: ['latin'],
    display: 'swap',
    variable: '--font-manrope',
    weight: ['400', '500', '600', '700', '800']
  });

  const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${manrope.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MobileNav />
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
