import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { Manrope } from 'next/font/google';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Manrope(
  { subsets: ['latin'],
    display: 'swap',
    variable: '--font-manrope',
    weight: ['400', '500', '600', '700', '800']
  });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${manrope.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
